#cloud-config
users:
  - default
  - name: hugo
packages:
  - hugo
  - git
runcmd:
  - su hugo - -c "git clone https://github.com/mattj-io/blog.git /home/hugo/mattj.blog"
  - su hugo - -c "git clone https://github.com/mattj-io/hugo-config.git /home/hugo/hugo-config"
  - ln -s /home/hugo/hugo-config/hugo.service /etc/systemd/system/hugo.service
  - su hugo - -c "cd /home/hugo/mattj.blog && git submodule init && git submodule update"
  - systemctl start hugo
